# POP3
pop3.host=localhost
pop3.port=1110

# Inbox login
email=secondemail@test.local
password=password123

# SMTP 
smtp.host=localhost
smtp.port=1025

from.email=reminders@local.test

# Reply targets , add as u feel like
reply.to.emails=tester1@test.com,tester2@test.com, tester3@test.com
