// Abdelrahman Ahmed u24898008 && Hamdaan Mirza 24631494

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class EventReminder {

    private static final int REMINDER_DAYS_AHEAD = 6;
    private static final String EVENTS_FILE = "events.txt";

    private static class Event {
        private final int day;
        private final int month;
        private final String description;

        Event(int day, int month, String description) {
            this.day = day;
            this.month = month;
            this.description = description;
        }
    }

    public static void readEventsFromFile(List<Event> events) {
        try (BufferedReader reader = new BufferedReader(new FileReader(EVENTS_FILE))) {
            String line;
            int lineNumber = 0;
            while ((line = reader.readLine()) != null) {
                lineNumber++;
                line = line.trim();
                if (line.isEmpty()) {
                    continue;
                }
                Event event = parseEvent(line, lineNumber);
                if (event != null) {
                    events.add(event);
                }
            }
        } catch (IOException e) {
            System.err.println("Could not read the events file: " + e.getMessage());
        }
    }

    private static Event parseEvent(String line, int lineNumber) {
        String[] parts = line.split("\\s+", 2);
        if (parts.length < 2) {
            System.err.println("Skipping malformed line " + lineNumber + ": " + line);
            return null;
        }
        String dateToken = parts[0].trim();
        String description = parts[1].trim();
        String[] dateParts = dateToken.split("/");
        if (dateParts.length != 2) {
            System.err.println("Skipping malformed date at line " + lineNumber + ": " + line);
            return null;
        }
        try {
            int day = Integer.parseInt(dateParts[0]);
            int month = Integer.parseInt(dateParts[1]);
            if (day < 1 || day > 31 || month < 1 || month > 12) {
                System.err.println("Skipping invalid date at line " + lineNumber + ": " + line);
                return null;
            }
            return new Event(day, month, description);
        } catch (NumberFormatException e) {
            System.err.println("Skipping non-numeric date at line " + lineNumber + ": " + line);
            return null;
        }
    }

    public static List<Event> getEventsToRemind(List<Event> events, LocalDate runDate) {
        LocalDate targetDate = runDate.plusDays(REMINDER_DAYS_AHEAD);
        int reminderDay = targetDate.getDayOfMonth();
        int reminderMonth = targetDate.getMonthValue();
        List<Event> matchingEvents = new ArrayList<>();
        for (Event event : events) {
            if (event.day == reminderDay && event.month == reminderMonth) {
                matchingEvents.add(event);
            }
        }
        return matchingEvents;
    }

    public static String buildEmailBody(List<Event> events, LocalDate runDate) {
        LocalDate targetDate = runDate.plusDays(REMINDER_DAYS_AHEAD);
        StringBuilder body = new StringBuilder();
        body.append("Reminder: these events occur in ")
                .append(REMINDER_DAYS_AHEAD)
                .append(" days (on ")
                .append(formatDateDM(targetDate))
                .append("):\r\n\r\n");

        for (Event event : events) {
            body.append("- ")
                    .append(String.format("%02d/%02d", event.day, event.month))
                    .append(" ")
                    .append(event.description)
                    .append("\r\n");
        }

        body.append("\r\nGenerated by EventReminder.");
        return body.toString();
    }

    private static String formatDateDM(LocalDate date) {
        return String.format("%02d/%02d", date.getDayOfMonth(), date.getMonthValue());
    }

    private static String readServerReply(BufferedReader in) throws IOException {
        String firstLine = in.readLine();
        if (firstLine == null) {
            throw new IOException("SMTP server closed connection unexpectedly.");
        }

        StringBuilder response = new StringBuilder(firstLine);
        while (firstLine.length() >= 4 && firstLine.charAt(3) == '-') {
            String continuation = in.readLine();
            if (continuation == null) {
                break;
            }
            response.append("\n").append(continuation);
            firstLine = continuation;
        }

        return response.toString();
    }

    private static void sendCommand(BufferedWriter out, String command) throws IOException {
        out.write(command + "\r\n");
        out.flush();
    }

    private static void checkReplyCode(String response, int expectedPrefix) throws IOException {
        if (!response.startsWith(String.valueOf(expectedPrefix))) {
            throw new IOException("SMTP error. Expected " + expectedPrefix + "xx but got: " + response);
        }
    }

    public static void sendEmail(
            String smtpHost, int smtpPort, String from, String to, String subject, String body) throws IOException {
        try (
                Socket socket = new Socket(smtpHost, smtpPort);
                BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                BufferedWriter out = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()))) {
            String response = readServerReply(in);
            checkReplyCode(response, 220);

            sendCommand(out, "HELO localhost");
            response = readServerReply(in);
            checkReplyCode(response, 250);

            sendCommand(out, "MAIL FROM:<" + from + ">");
            response = readServerReply(in);
            checkReplyCode(response, 250);

            sendCommand(out, "RCPT TO:<" + to + ">");
            response = readServerReply(in);
            checkReplyCode(response, 250);

            sendCommand(out, "DATA");
            response = readServerReply(in);
            checkReplyCode(response, 354);

            out.write("From: " + from + "\r\n");
            out.write("To: " + to + "\r\n");
            out.write("Subject: " + subject + "\r\n");
            out.write("\r\n");
            out.write(body + "\r\n");
            out.write(".\r\n");
            out.flush();

            response = readServerReply(in);
            checkReplyCode(response, 250);

            sendCommand(out, "QUIT");
            response = readServerReply(in);
            checkReplyCode(response, 221);
        }
    }

    public static void main(String[] args) {
        if (args.length < 4) {
            System.out.println("How to use the program: java EventReminder <smtpHost> <smtpPort> <fromEmail> <toEmail>");
            System.out.println("Example: java EventReminder localhost 25 reminders@local.test you@local.test");
            return;
        }

        String smtpHost = args[0];
        int smtpPort;

        try {
            smtpPort = Integer.parseInt(args[1]);
        } catch (NumberFormatException e) {
            System.err.println("Invalid SMTP port: " + args[1]);
            return;
        }

        String fromAddress = args[2];
        String toAddress = args[3];

        List<Event> allEvents = new ArrayList<>();
        readEventsFromFile(allEvents);

        LocalDate today = LocalDate.now();
        List<Event> reminders = getEventsToRemind(allEvents, today);

        if (reminders.isEmpty()) {
            System.out.println("No email was sent beaucse there are no events coming up in " + REMINDER_DAYS_AHEAD + " days.");
            return;
        }

        LocalDate reminderDate = today.plusDays(REMINDER_DAYS_AHEAD);
        String subject = "Event reminder for " + formatDateDM(reminderDate);
        String body = buildEmailBody(reminders, today);

        try {
            sendEmail(smtpHost, smtpPort, fromAddress, toAddress, subject, body);
            System.out.println("An email to" + toAddress + " with " + reminders.size() + " event(s) info was sent as a reminder.");
        } catch (IOException e) {
            System.err.println("Failed to send an email: " + e.getMessage());
        }
    }
}